package com.bank.bian.quotedsecuritiesservice;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Quoted Securities Service
 *
 * Business Area:      Reference Data
 * Business Domain:    Reference Data
 * Functional Pattern: Catalog
 * Asset Type:         Securities Reference Data
 * Control Record:     Securities Reference Data Directory Entry
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Quoted Securities Service — BIAN Semantic API")
                .description("Service Domain 'Quoted Securities Service' (Catalog pattern) "
                        + "operating on the 'Securities Reference Data Directory Entry' control record.")
                .version("0.1.0"));
    }
}
